addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("org.foundweekends.conscript" % "sbt-conscript" % "0.5.5")
addSbtPlugin("com.github.sbt" % "sbt-release" % "1.0.15")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.6")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.10.0")
